# all dates are in YYYY-MM-DD format
[contract]
version = "2023"  # can be "2016", "2023"
require_insurance = true
require_tenants_insurance = false

[sign]
date = "<today_plus> 1"  # can be "<today>", "<today_plus> n", "<blank_date>", or a date
location = "ישראל"
protocol_date = "<sign_date>"  # can be "<sign_date>", "<blank_date>", or a date

[landlord]
name = "________________________"
city = "__________________"
address = "________________________________________________"
id = "____________"
phone = "______-______________"

[[tenants]]
name = "________________________"
city = "__________________"
address = "________________________________________________"
id = "____________"
phone = "______-______________"

[[tenants]]
name = "________________________"
city = "__________________"
address = "________________________________________________"
id = "____________"
phone = "______-______________"

# add more tenants as needed

[property]
city = "__________________"
address = "________________________________________________"
n_rooms = "____"
additions = "________________"

[period]
n_months = 24
start_date = "<sign_date>"  # can be "<sign_date>", "<blank_date>", or a date
end_date = "<from_start_date>"  # can be "<from_start_date>", "<blank_date>", or a date

[payment]
ils_per_month = 4000
day = "<start_date|day>"  # can be "<start_date|day>", "<blank_digit>", or a number between 1 to 31
mode = "checks"  # can be "bank-transfer", "checks"

[extend_option]
n_months = 12  # use 0 to disable
max_raise_percent = 5

[payment.bank_transfer]
bank_name = "________________________"
account_number = "____ - ______ - ________________________"

[assurance]
mode = "bank-guarantee"  # can be "promissory", "bank-guarantee"

[assurance.bank_guarantee]
amount = "<months> 3"  # can be "<months> n", or a number

[assurance.promissory.guarantee]
name = "________________________"
id = "____________"
address_full = "__________________________________________________________________"
lawyer_name = "________________________"
date = "<blank_date>"  # can be "<blank_date>", or a date  # remove

[assurance.promissory.form]
amount = "<months> 6"  # can be "<months> n", or a number
sign_location = "<sign_location>"  # can be "<sign_location>", or a string
date = "<sign_date>"  # can be "<sign_date>", "<blank_date>", or a date
base_rate = "______"

[assurance.promissory.received]
time = "____________"
location = "________________________"
