repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # filesystem
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # git
      - id: check-added-large-files
      - id: check-merge-conflict
      # secrets
      - id: detect-private-key
      # text in files
      - id: end-of-file-fixer
        exclude: "^output/lease-blank.md$"
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        exclude: "^output/lease-blank.md$"
      # python
      - id: check-ast
        fail_fast: true
      - id: check-docstring-first
      - id: debug-statements
      - id: requirements-txt-fixer
      # filetypes
      - id: check-json
        exclude: ipynb
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: pretty-format-json
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-tabs
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.4
    hooks:
      - id: ruff
        alias: ruff-isort
        args: ["--select", "I001", "--fix"]
      - id: ruff-format
      - id: ruff
  - repo: local
    hooks:
      - id: create-blank-lease
        name: create blank lease
        entry: poetry run src/render.py -U --simple -i input_files/blank.toml -o output/lease-blank.md
        language: system
        always_run: true
        pass_filenames: false
ci:
  skip:
    - create-blank-lease
  autoupdate_schedule: quarterly
